# -*- coding: utf-8 -*-
"""vehicle fuel efficiency_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqHpkm0JcXRqLJtgaKbIGiEZyNx06mN4
"""

import streamlit as st
import pandas as pd
import joblib

# Load trained model and encoders
model = joblib.load("vehicle_fuel_model.pkl")
encoder = joblib.load("label_encoder.pkl")

st.title("Vehicle Fuel Efficiency Prediction App")

st.write("Enter vehicle details below:")

# Numerical Inputs
cylinders = st.number_input("Cylinders", min_value=3, max_value=12)
engine_size = st.number_input("Engine Size (Liters)", min_value=0.5, max_value=10.0)
horsepower = st.number_input("Horsepower", min_value=40, max_value=500)
weight = st.number_input("Weight", min_value=1000, max_value=6000)
acceleration = st.number_input("Acceleration", min_value=5.0, max_value=30.0)
model_year = st.number_input("Model Year", min_value=1970, max_value=2025)

# Categorical Input
origin = st.selectbox("Origin", encoder["Origin"].classes_)

# Create DataFrame
df = pd.DataFrame({
    "Cylinders": [cylinders],
    "Engine Size": [engine_size],
    "Horsepower": [horsepower],
    "Weight": [weight],
    "Acceleration": [acceleration],
    "Model Year": [model_year],
    "Origin": [origin]
})

# Predict Button
if st.button("Predict Fuel Efficiency"):

    # Encode categorical columns
    for col in encoder:
        df[col] = encoder[col].transform(df[col])

    prediction = model.predict(df)

    st.success(f"Predicted Fuel Efficiency (MPG): {prediction[0]:.2f}")
